swagger: "2.0"
info:
  title: "Swagger Play"
  description: "Test application"
  version: "3.0.0"
consumes:
  - application/json
  - application/text
produces:
  - application/json
  - application/text
paths:
  /name:
    get:
      #query parameters
      parameters:
        - name: name
          in: query
          required: true
          type: string
      responses:
        #response code
        200:
          description: Successful response






